# Use custom format
format = """
$username\
$hostname\
$shlvl\
$singularity\
$directory\
$python\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$cmake\
$cobol\
$dart\
$deno\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

right_format = """$kubernetes"""

[kubernetes]
format = '☸ [$context](bold green)'
disabled = false

[python]
format = 'via $symbol(${version} )(($virtualenv) )'
pyenv_version_name = true

